---
language: ruby
before_install:
  - rm Gemfile.lock || true
  - rm .ruby-* || true
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
# Kept around for reference but not needed
#script: bundle exec rake
env:
  matrix:
    - PUPPET_VERSION="~> 2.7.0"
    - PUPPET_VERSION="~> 3.0.0"
    - PUPPET_VERSION="~> 3.2.0"
    - PUPPET_VERSION="~> 3.3.0"
notifications:
  email: false
